# CPP Standard
foreach(i ${CMAKE_CXX_COMPILE_FEATURES})
    if (i STREQUAL cxx_std_20)
        set(has_cxx_std_20 TRUE)
    endif()
endforeach()
if (has_cxx_std_20)
    option(ENABLE_CPP_20 "Enable CPP 20" ON)
else ()
    option(ENABLE_CPP_20 "Enable CPP 20" OFF)
endif()
if (ENABLE_CPP_20)
    set(CMAKE_CXX_STANDARD 20)
else()
    set(CMAKE_CXX_STANDARD 17)
endif()
set(CMAKE_CXX_STANDARD_REQUIRED ON)
message(STATUS "CXX Standard: ${CMAKE_CXX_STANDARD}")
